version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/chi
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/echo
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/fiber
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/gin
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/gorilla
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/httprouter
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples/openapi/stdhttp
    schedule:
      interval: weekly
