name: ci - lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint.yml@d81a558a5be315cf44082bf5aedc19e7244ebd27
    permissions:
      pull-requests: read
