name: cd - release

on:
  push:
    branches: [main]
jobs:
  release:
    uses: natalie-o-perret/.github/.github/workflows/reusable-release.yml@d81a558a5be315cf44082bf5aedc19e7244ebd27
    permissions:
      contents: write
