a tout le monde, désolé pour les gens loin et les gens qui ne se présentent pas. Certains on déjà pu me rencontrer et une vidéo a été tournée...

Mais toujours iname: yaml-lint

on:
  push:
    branches: [main]
    paths: ["**/*.yml", "**/*.yaml", ".yamllint.yml"]
  pull_request:
    branches: [main]
    paths: ["**/*.yml", "**/*.yaml", ".yamllint.yml"]

jobs:
  lint-yaml:
    name: lint yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install yamllint
        run: pip install yamllint

      - name: run yamllint
        run: yamllint -c .yamllint.yml .
